### ISSUE TITLE
Concurrency is not being optimized

### ISSUE THREAD

**Issue by adriangb** [simonw/asyncinject#10]
It looks like concurrency / parallelism is not being maximized due to the grouping of dependencies into node groups. Here's a simple example:

```python
import asyncio
from time import time
from typing import Annotated

async def a():
    await asyncio.sleep(1)

async def b():
    await asyncio.sleep(2)

async def c(a):
    await asyncio.sleep(1)

async def d(b, c):
    pass

async def main_asyncinjector():
    reg = Registry(a, b, c, d)
    start = time()
    await reg.resolve(d)
    print(time()-start)

asyncio.run(main_asyncinjector())
```

This should take 2 seconds to run (start `a` and `b`, once `a` finishes start `c`, `b` and `c` finish at the same time and you're done) but takes 3 seconds (start `a` and `b`, wait for both to finish then start `c`).

This happens because `graphlib.TopologicalSorter` is not used online and instead it is being used to statically compute groups of dependencies.

I don't think it would be too hard to address this, but I'm not sure how much you'd want to change to accommodate this.
I work on a similar project ([https://github.com/adriangb/di](https://github.com/adriangb/di/blob/main/di/executors/_async.py)) and there I found it very useful to break out the concept of an "executor" out of the container/registry concept, which means that instead of a `parallel` option you'd have pluggable executors that could choose to use concurrency, limit concurrency, use threads instead, etc.
FWIW here's what that looks like with this example:

```python
import asyncio
from time import time
from typing import Annotated

from asyncinject import Registry
from di.dependant import Marker, Dependant
from di.container import Container
from di.executors import ConcurrentAsyncExecutor


async def a():
    await asyncio.sleep(1)

async def b():
    await asyncio.sleep(2)

async def c(a: Annotated[None, Marker(a)]):
    await asyncio.sleep(1)

async def d(b: Annotated[None, Marker(b)], c: Annotated[None, Marker(c)]):
    pass

async def main_asyncinjector():
    reg = Registry(a, b, c, d)
    start = time()
    await reg.resolve(d)
    print(time()-start)


async def main_di():
    container = Container()
    solved = container.solve(Dependant(d), scopes=[None])
    executor = ConcurrentAsyncExecutor()
    async with container.enter_scope(None) as state:
        start = time()
        await container.execute_async(solved, executor, state=state)
        print(time()-start)

asyncio.run(main_asyncinjector())  # 3 seconds
asyncio.run(main_di())  # 2 seconds
```

**Comment by simonw** [comment]
This is a really good catch, thank you.

I'm going to mull on this one and see if I can come up with a way to start executing other necessary steps earlier, as shown in your example.

**Comment by adriangb** [comment]
Sounds good! I think it should be pretty straightforward:
- if `parallel=False` then just call dependencies in order as returned by `TopologicalSorter.static_order()`
- if `parallel=True` then you do something similar to [here](https://github.com/adriangb/di/blob/566c15a7b7bfa738b3ec237083b343b5368dd97d/di/executors/_async.py#L50-L53) where you wrap each dependency so that when it is done executing it calls `asyncio.create_task()` for every newly available dependency.

I think it can be done without any API changes, let me know if you'd be interested in a PR.

**Comment by simonw** [comment]
If you're interested in making a PR I would be delighted to review it! I was thinking this through and looking at `asyncio.as_completed()` but I think your suggestion there likely makes more sense.

**Comment by simonw** [comment]
I wrote a visualization function to help illustrate this fix:

```python
def visualize_traces(traces, chars=80):
    start = min(t[1] for t in traces)
    end = max(t[2] for t in traces)
    width = end - start
    pos = lambda value1, value2: int((value1 - value2) * chars / width)
    for trace in traces:
        name, p1, p2 = trace[0], pos(trace[1], start), pos(trace[2], trace[1])
        print("{}: started {:5f}, took {:5f}".format(name, trace[1] - start, trace[2] - trace[1]))
        print(' ' * p1, '*' * p2)
```
Then I ran the example you provided like so:
```python
import asyncio
from asyncinject import Registry

async def a():
    await asyncio.sleep(1)

async def b():
    await asyncio.sleep(2)

async def c(a):
    await asyncio.sleep(1)

async def d(b, c):
    pass

registry = Registry(a, b, c, d)
collected = []
registry.timer = lambda name, start, end: collected.append((name, start, end))
await registry.resolve(d)
visualize_traces(collected)
```
Prior to this fix, the generated visualization looked like this - for a total of about 3s
```
a: started 0.000025, took 1.000724
 **************************
b: started 0.000000, took 2.000811
 *****************************************************
c: started 2.000981, took 1.000151
                                                      **************************
d: started 3.001329, took 0.000001
```
After applying the fix, that changes to this (a total of about 2s):
```
a: started 0.000022, took 1.000659
 ****************************************
b: started 0.000000, took 2.000802
 *******************************************************************************
c: started 1.000875, took 1.000121
                                         ***************************************
d: started 2.001063, took 0.000000
```
`c` can now start as soon as its single dependency, `a`, has finished. Previously it would also work for the unrelated dependency `b` to finish too.

**Comment by adriangb** [comment]
Very cool!
